### ISSUE TITLE
Add missing columns in table_azure_servicebus_namespace

### ISSUE THREAD

**Issue by c0d3r-arnab** [turbot/steampipe-plugin-azure#365] opened 2021-10-01 06:56 UTC
Reference link: https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/servicebus/mgmt/2021-06-01-preview/servicebus

**Comment by misraved** [comment] 2022-06-02 15:10
Closing this since the issue is not on priority.

**Closed by misraved** 2022-06-02 15:10 UTC
Labels: enhancement
